language: haskell
before_install:
  - sudo apt-get install -qq tokyotyrant libtokyotyrant-dev
  - cp .travis/etc/default/tokyotyrant /etc/default/tokyotyrant
  - service tokyotyrant start
script:
  - cabal configure --enable-tests && cabal build && cabal test --show-details=always
