name: monarch
version: "0.10.0.1"
synopsis: Monadic interface for TokyoTyrant.
description: This package provides simple monadic interface for TokyoTyrant.
category: Database
author: Noriyuki OHKAWA <n.ohkawa@gmail.com>
maintainer: Noriyuki OHKAWA <n.ohkawa@gmail.com>
license: BSD3
github: notogawa/monarch
dependencies:
  - base ==4.*
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
    - Database.Monarch
    - Database.Monarch.Mock
  dependencies:
    - containers >=0.4
    - bytestring >=0.9
    - binary >=0.5
    - network >=2.3
    - resource-pool >=0.1
    - monad-control >=0.3
    - mtl >=2.1
    - lifted-base >=0.1
    - transformers >=0.3
    - transformers-base >=0.4
    - stm >=2.3
tests:
  doctests:
    main: doctests.hs
    source-dirs: test
    dependencies:
      - doctest
  specs:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - monarch
      - bytestring
      - transformers
      - hspec >=1.3
    when:
      - condition: ! "!(flag(develop))"
        buildable: false
benchmarks:
  benchmark:
    main: benchmark.hs
    source-dirs: test
    dependencies:
      - monarch
      - tokyotyrant-haskell
      - bytestring
      - criterion
    when:
      - condition: ! "!(flag(develop))"
        buildable: false
flags:
  develop:
    description: For developer
    manual: false
    default: false
tested-with: ghc ==9.4.8
